build:
    environment:
        php:
            version: '8.2'
    nodes:
        analysis:
            dependencies:
                after:
                    - composer require --dev "squizlabs/php_codesniffer=3.9.1"
            project_setup:
                override:
                    - 'true'
            tests:
                override:
                    - php-scrutinizer-run
                    -
                        command: phpcs-run
                        use_website_config: true
    tests:
        override:
            command: "php -v"
filter:
    excluded_paths:
        - 'tests/*'
checks:
    php: true
coding_style:
    php: {  }
