name: Mutation Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    runs-on: ubuntu-latest

    name: Mutation Testing Code Review Annotations ${{ matrix.php-version }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          tools: composer:v2
          extensions: pcov
          coverage: pcov

      - name: Install dependencies
        run: |
          composer install --no-progress --no-interaction

      - name: Download Infection
        run: |
          wget https://github.com/infection/infection/releases/download/0.26.19/infection.phar
          chmod +x infection.phar

      - name: Run Infection for added files only
        if: github.event_name == 'pull_request'
        run: |
          git fetch --depth=1 origin $GITHUB_BASE_REF
          php infection.phar -j8 --git-diff-filter=A --git-diff-base=origin/$GITHUB_BASE_REF --logger-github --ignore-msi-with-no-mutations --only-covered

      - name: Run Infection for all files
        if: github.event_name == 'push'
        env:
            INFECTION_BADGE_API_KEY: ${{ secrets.INFECTION_BADGE_API_KEY }}
        run: |
            php infection.phar -j8 --ignore-msi-with-no-mutations --only-covered
